import 'package:flutter/material.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl2widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl2widget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl2widget/generated/GeneratedXPLOREWidget.dart';

/* Frame Google Pixel 2 XL - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomePageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 411.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -44.0,
                  top: -33.0,
                  right: null,
                  bottom: null,
                  width: 500.0,
                  height: 889.0,
                  child: GeneratedImage1Widget(),
                ),
                Positioned(
                  left: 150.0,
                  top: 77.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 110.0,
                  child: GeneratedEllipse2Widget(),
                ),
                Positioned(
                  left: 102.0,
                  top: 187.0,
                  right: null,
                  bottom: null,
                  width: 214.0,
                  height: 67.0,
                  child: GeneratedXPLOREWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
