import 'package:flutter/material.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedManaliisahighaltitudeHimalayanresorttowninIndiasnorther.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedAdd_locationWidget5.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedCloud_downloadWidget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedMANALIWidget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl3widget/generated/GeneratedGroup9Widget.dart';

/* Frame Google Pixel 2 XL - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1016.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 411.0,
                            height: 1016.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 411.0,
                                    height: 384.0,
                                    child: GeneratedRectangle2Widget(),
                                  ),
                                  Positioned(
                                    left: 9.0,
                                    top: 61.0,
                                    right: null,
                                    bottom: null,
                                    width: 202.0,
                                    height: 63.0,
                                    child: GeneratedMANALIWidget(),
                                  ),
                                  Positioned(
                                    left: 320.0,
                                    top: 332.0,
                                    right: null,
                                    bottom: null,
                                    width: 80.0,
                                    height: 80.0,
                                    child: GeneratedEllipse1Widget(),
                                  ),
                                  Positioned(
                                    left: 335.0,
                                    top: 347.0,
                                    right: null,
                                    bottom: null,
                                    width: 50.0,
                                    height: 50.0,
                                    child: GeneratedAdd_locationWidget5(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 707.0,
                                    right: null,
                                    bottom: null,
                                    width: 335.0,
                                    height: 270.0,
                                    child: GeneratedGroup6Widget(),
                                  ),
                                  Positioned(
                                    left: 12.0,
                                    top: 412.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 54.0,
                                    child: GeneratedRectangle8Widget(),
                                  ),
                                  Positioned(
                                    left: 91.0,
                                    top: 412.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 54.0,
                                    child: GeneratedRectangle9Widget(),
                                  ),
                                  Positioned(
                                    left: 345.0,
                                    top: 412.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 54.0,
                                    child: GeneratedRectangle12Widget(),
                                  ),
                                  Positioned(
                                    left: 170.0,
                                    top: 412.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 54.0,
                                    child: GeneratedRectangle10Widget(),
                                  ),
                                  Positioned(
                                    left: 255.0,
                                    top: 412.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 54.0,
                                    child: GeneratedRectangle11Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 495.0,
                                    right: null,
                                    bottom: null,
                                    width: 365.0,
                                    height: 185.0,
                                    child: GeneratedGroup9Widget(),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 503.0,
                                    right: null,
                                    bottom: null,
                                    width: 357.0,
                                    height: 169.0,
                                    child:
                                        GeneratedManaliisahighaltitudeHimalayanresorttowninIndiasnorther(),
                                  ),
                                  Positioned(
                                    left: 9.0,
                                    top: 332.0,
                                    right: null,
                                    bottom: null,
                                    width: 78.0,
                                    height: 78.0,
                                    child: GeneratedEllipse3Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 755.0,
              right: null,
              bottom: null,
              width: 411.0,
              height: 68.0,
              child: GeneratedGroup7Widget(),
            ),
            Positioned(
              left: 31.0,
              top: 355.0,
              right: null,
              bottom: null,
              width: 34.0,
              height: 38.0,
              child: GeneratedCloud_downloadWidget(),
            )
          ]),
    ));
  }
}
