import 'package:flutter/material.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedGroup7Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedMANALIWidget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedAdd_locationWidget6.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GenerateddetailsaboutthisplaceWidget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedVectorWidget24.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedTrysayingWidget.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedManaliisahighaltitudeHimalayanresorttowninIndiasnorther1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/hackathon_20gecapp/generatedgooglepixel2xl7widget/generated/GeneratedRectangle10Widget1.dart';

/* Frame Google Pixel 2 XL - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGooglePixel2XL7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 823.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 384.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 9.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 63.0,
                child: GeneratedMANALIWidget1(),
              ),
              Positioned(
                left: 320.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 335.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedAdd_locationWidget6(),
              ),
              Positioned(
                left: 40.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 270.0,
                child: GeneratedGroup6Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 54.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 91.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 54.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 345.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 54.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 170.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 54.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 255.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 54.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 169.0,
                child:
                    GeneratedManaliisahighaltitudeHimalayanresorttowninIndiasnorther1(),
              ),
              Positioned(
                left: 0.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 68.0,
                child: GeneratedGroup7Widget1(),
              ),
              Positioned(
                left: -6.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 335.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 45.0,
                child: GeneratedTrysayingWidget(),
              ),
              Positioned(
                left: 62.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 31.0,
                child: GenerateddetailsaboutthisplaceWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.08759124087591241;
                  double scaleX = (constraints.maxWidth * percentWidth) / 36.0;

                  double percentHeight = 0.05953827460510328;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 49.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.45255474452554745,
                        translateY: constraints.maxHeight * 0.8140947752126367,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget24())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
